on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["24.0"]
        elixir: ["1.12.3"]
    services:
      postgres:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
          MIX_TEST_PARTITION: 1
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix compile

      - name: Mix Format & DB
        run: |
          mix format --check-formatted
          mix ecto.migrate

      - name: Run Tests
        run: mix coveralls.github
        env:
          MIX_TEST_PARTITION: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}